global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node-backend'
    static_configs:
      - targets: ['backend:4000'] 
      # 'backend' matches the service name we are about to write in docker-compose